### ISSUE TITLE
Adding styles to the UI and make attractive

### ISSUE THREAD

**Issue by mastrmind-dev** [mastrmind-dev/electron-screen-recorder#1]
This task is beginner friendly one. If anyone who has knowledge on HTML and CSS can contribute to this. Just add a CSS file and make attractive the home window's user interface.

This is really important. Because any one can contribute to this and I would merge all the PRs which have good UI enhancements.

**Comment by AyushmanSinghRajawat** [comment]
Hey @mastrmind-dev , I have a pretty great understanding in creating attractive UI. I am excited to contribute to this project.
Please assign me this issue, and i will get started on this asap.

**Comment by AyushmanSinghRajawat** [comment]
Please let me know if you have any issues with the UI.
