### ISSUE TITLE
Add "Select screen" button

### ISSUE THREAD

**Issue by mastrmind-dev** [mastrmind-dev/electron-screen-recorder#2]
In main.js file, Menu.BuildFromTemplate (26th line) generates a popup to select the screen that the user wants to record. But when the application opens, that popup comes from nowhere. Instead, having a 'select screen' button would be ideal to show that popup.

**Comment by kritikash18** [comment]
Hi @mastrmind-dev , I would like to work on this issue

**Comment by mastrmind-dev** [comment]
Thank You For Volunteering

**Comment by kritikash18** [comment]
Raised PR #8

**Comment by mastrmind-dev** [comment]
@kritikash18 I need just a small thing to know. you made this pr with the same email that you have logged to github?

**Comment by kritikash18** [comment]
@mastrmind-dev yes, the account name might have mixed up with github config I had set previously
