### ISSUE TITLE
adding a notification popup

### ISSUE THREAD

**Issue by mastrmind-dev** [mastrmind-dev/electron-screen-recorder#4]
when user records the screen, there should be a notification popup which says "recording the screen" and the notification can be minimized or hide.

**Comment by AyushmanSinghRajawat** [comment]
Hey @mastrmind-dev , I know how to add this feature and would like to contribute to this project. Please assign me this issue.

**Comment by mastrmind-dev** [comment]
If anything to discuss, just drop a comment (regarding both the tasks you got). Thank you for being a volunteer
